### ISSUE TITLE
[Question] Build from linux

### ISSUE THREAD

**Issue by scmanjarrez** [ShadixAced/Championify#2]
Hi,
I would like to compile an exe file from linux, do you mind sharing the steps? Tried with
`npm i`
`npm run build` 
but no success at all, failed with error 

> /home/kubuntu/Championify/node_modules/bluebird/js/release/promisify.js:54
                    throw new TypeError("Cannot promisify an API that has normal methods with '%s'-suffix\u000a\u000a    See http://goo.gl/MqrFmX\u000a"
 
Even tried compiling using electron
`electron-packager Championify championify --platform=win32 --arch=x64`
seemed to generate the exe but got an error on execution.

> A JavaScript error occurred in the main process[Content]Uncaught Exception:C:\Riot Games\championify-win32-x64\resources\app\electron.js:1import { app, BrowserWindow } from 'electron';^SyntaxError: Unexpected token {at Module._compile (internal/modules/cjs/loader.js:722:23)at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)at Module.load (internal/modules/cjs/loader.js:645:32)at Function.Module._load (internal/modules/cjs/loader.js:560:12)at Object.<anonymous> (C:\Riot Games\championify-win32-x64\resources\electron.asar\browser\init.js:181:12)at Module._compile (internal/modules/cjs/loader.js:786:30)at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)at Module.load (internal/modules/cjs/loader.js:645:32)at Function.Module._load (internal/modules/cjs/loader.js:560:12)at Function.Module.runMain (internal/modules/cjs/loader.js:850:10)

Using node 10.16.3
Electron-packager 14.0.6

**Comment by ShadixAced** [comment]
Hello, and thanks for telling us. 
As of now, since I am recoding what Dustin has done almost from scratch, building might be failing. From what I see, it is due to a Promisify on an async function. 
Had it on AWS-SDK though, which is why i use an older version. 
It is though the first time I see this error coming from Electron...

**Comment by ShadixAced** [comment]
I suppose that your "npm i" didn't work really well... seems that it couldn't find anything related to the electron package.

**Comment by Leafgard** [comment]
It looks like there's already an electron import error using electron-packager so I assume @ShadixAced has right ! :/ Have you got some logs about npm install, or did it install all packages as usual ?

**Comment by scmanjarrez** [comment]
Thanks for your prompt response! Here is the log of npm  install
> ➜  Championify git:(master) ✗ npm install                                                                                                                                       
>                                                                                                                                                                                 
> fs-xattr@0.3.0 install /home/kubuntu/Championify/node_modules/fs-xattr                                                                                                        
> node-gyp rebuild                                                                                                                                                              
>                                                                                                                                                                                 
> make: Entering directory '/home/kubuntu/Championify/node_modules/fs-xattr/build'                                                                                                
>   CC(target) Release/obj.target/xattr/src/async.o                                                                                                                               
>   CC(target) Release/obj.target/xattr/src/error.o                                                                                                                               
>   CC(target) Release/obj.target/xattr/src/sync.o                                                                                                                                
>   CC(target) Release/obj.target/xattr/src/util.o                                                                                                                                
>   CC(target) Release/obj.target/xattr/src/xattr.o                                                                                                                               
>   SOLINK_MODULE(target) Release/obj.target/xattr.node                                                                                                                           
>   COPY Release/xattr.node                                                                                                                                                       
> make: Leaving directory '/home/kubuntu/Championify/node_modules/fs-xattr/build'                                                                                                 
>                                                                                                                                                                                 
> v8-profiler-next@1.1.1 install /home/kubuntu/Championify/node_modules/v8-profiler-next                                                                                        
> node-gyp rebuild                                                                                                                                                              
>                                                                                                                                                                                 
> make: Entering directory '/home/kubuntu/Championify/node_modules/v8-profiler-next/build'                                                                                        
>    CXX(target) Release/obj.target/profiler/src/profiler.o                                                                                                                        
>    CXX(target) Release/obj.target/profiler/src/cpu_profiler.o                                                                                                                    
>    CXX(target) Release/obj.target/profiler/src/cpu_profile.o                                                                                                                     
>    CXX(target) Release/obj.target/profiler/src/cpu_profile_node.o                                                                                                                
>    CXX(target) Release/obj.target/profiler/src/heap_profiler.o
>    CXX(target) Release/obj.target/profiler/src/heap_snapshot.o
>    CXX(target) Release/obj.target/profiler/src/heap_output_stream.o
>    CXX(target) Release/obj.target/profiler/src/heap_graph_node.o
>    CXX(target) Release/obj.target/profiler/src/heap_graph_edge.o
>    CXX(target) Release/obj.target/profiler/src/sampling_heap_profile.o
>    SOLINK_MODULE(target) Release/obj.target/profiler.node
>    COPY Release/profiler.node
> make: Leaving directory '/home/kubuntu/Championify/node_modules/v8-profiler-next/build'
> 
> electron@6.0.11 postinstall /home/kubuntu/Championify/node_modules/electron
> node install.js
> 
> 
> championify@2.1.6 postinstall /home/kubuntu/Championify
> gulp postinstall
> 
> [23:15:45] Requiring external module @babel/register
> /home/kubuntu/Championify/node_modules/bluebird/js/release/promisify.js:54
>                     throw new TypeError("Cannot promisify an API that has normal methods with '%s'-suffix\u000a\u000a    See http://goo.gl/MqrFmX\u000a"
>                     ^
> 
> TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
> 
>     See http://goo.gl/MqrFmX
> 
>     at checkValid (/home/kubuntu/Championify/node_modules/bluebird/js/release/promisify.js:54:27)
>     at promisifiableMethods (/home/kubuntu/Championify/node_modules/bluebird/js/release/promisify.js:77:5)
>     at promisifyAll (/home/kubuntu/Championify/node_modules/bluebird/js/release/promisify.js:241:9)
>     at Function.Promise.promisifyAll (/home/kubuntu/Championify/node_modules/bluebird/js/release/promisify.js:311:12)
>     at Object.promisifyAll (/home/kubuntu/Championify/tasks/coverage.js:21:20)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Module._compile (/home/kubuntu/Championify/node_modules/pirates/lib/index.js:99:24)
>     at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Object.newLoader [as .js] (/home/kubuntu/Championify/node_modules/pirates/lib/index.js:104:7)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at requireDir (/home/kubuntu/Championify/node_modules/require-dir/index.js:128:33)
>     at Object.<anonymous> (/home/kubuntu/Championify/gulpfile.babel.js:6:1)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! championify@2.1.6 postinstall: `gulp postinstall`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the championify@2.1.6 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!    
> /home/kubuntu/.npm/_logs/2019-10-09T21_15_48_988Z-debug.log
[2019-10-09T21_15_48_988Z-debug.log](https://github.com/ShadixAced/Championify/files/3709496/2019-10-09T21_15_48_988Z-debug.log)

Sorry, seems that I didn't express myself well, the async error was from running "npm install". 
Since it didn't work I tried using electron-packager that generated the javascript error mentioned in the first comment.

**Comment by ShadixAced** [comment]
I've verified it, was on the electron.js file. I'm working on it, seems that Electron doesn't really like imports and prefer consts.

**Comment by ShadixAced** [comment]
Solved in the latest source releases, blank screen for now, but as said, it's in a early state.
